/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Boneco_Completo.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, forwardRef, useImperativeHandle } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { RapierRigidBody } from '@react-three/rapier'
import { M4A1 } from './M4A1'
import type { M4A1Ref } from './M4A1'

type ActionName =
  | 'mixamo.com'
  | 'Take 001'
  | 'sprint backward'
  | 'sprint left'
  | 'sprint right'
  | 'turn 90 right'
  | 'walk backward left'
  | 'walk backward right'
  | 'walk backward'
  | 'walk crouching backward left'
  | 'walk crouching backward right'
  | 'walk crouching backward'
  | 'walk crouching forward left'
  | 'walk crouching forward'
  | 'walk crouching left'
  | 'walk crouching right'
  | 'walk forward left'
  | 'walk forward right'
  | 'walk forward'
  | 'walk left'
  | 'walk right'
  | 'idle crouching'
  | 'idle'
  | 'run backward left'
  | 'run backward right'
  | 'run backward'
  | 'run forward left'
  | 'run forward right'
  | 'run forward'
  | 'run left'
  | 'run right'
  | 'sprint forward left'
  | 'sprint forward right'
  | 'sprint forward'
  | 'turn 90 left'
  | 'walk crouching forward right'
  | 'crouching turn 90 left'
  | 'crouching turn 90 right'
  | 'death crouching headshot front'
  | 'death from back headshot'
  | 'death from front headshot'
  | 'death from right'
  | 'death from the back'
  | 'death from the front'
  | 'idle aiming'
  | 'idle crouching aiming'
  | 'jump down'
  | 'jump loop'
  | 'jump up'
  | 'sprint backward left'
  | 'sprint backward right'
  | 'Sprinting Forward Roll'



type BonecoProps = React.ComponentProps<'group'> & {
  bodyRef: React.RefObject<RapierRigidBody | null>;
  isShootingRef: React.RefObject<boolean>;
  moveStateRef: React.RefObject<'run' | 'sprint' | 'walk' | 'crouch' | 'roll'>;
};

export interface BonecoRef {
  getMuzzlePosition: () => THREE.Vector3;
}

export const BonecoCompleto = forwardRef<BonecoRef, BonecoProps>(({ bodyRef, isShootingRef, moveStateRef, ...props }, ref) => {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Player.glb')

  // Mixamo Root Motion Fix ("In Place" hook)
  const inPlaceAnimations = React.useMemo(() => {
    return animations.map(clip => {
      const clonedClip = clip.clone();
      clonedClip.tracks.forEach(track => {
        // Check for the main hip translation track
        if (track.name.match(/mixamorigHips\.position/i)) {
          // track.values is a flat array [X, Y, Z, X, Y, Z, ...]
          for (let i = 0; i < track.values.length; i += 3) {
            // Zero out X and Z (Forward/Lateral movement)
            track.values[i] = 0;
            // Keep Y (track.values[i + 1]) for bounce/bobbing
            track.values[i + 2] = 0;
          }
        }
      });
      return clonedClip;
    });
  }, [animations]);

  const clone = React.useMemo(() => {
    const clonedScene = SkeletonUtils.clone(scene);
    clonedScene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
    return clonedScene;
  }, [scene]);

  const weaponGroupRef = useRef<THREE.Group>(null);
  const weaponRef = useRef<M4A1Ref>(null);
  const rightHandBone = React.useMemo(() => {
    let handBone: THREE.Bone | null = null;
    clone.traverse((child) => {
      if (child instanceof THREE.Bone && child.name === 'mixamorigRightHand') {
        handBone = child;
      }
    });
    return handBone;
  }, [clone]);

  React.useEffect(() => {
    if (rightHandBone && weaponGroupRef.current) {
      const bone = rightHandBone as THREE.Bone;
      bone.add(weaponGroupRef.current);
    }
  }, [rightHandBone]);

  const { actions } = useAnimations(inPlaceAnimations, group)

  const currentAction = useRef<ActionName>('idle');

  // Play initial animation
  useEffect(() => {
    actions[currentAction.current]?.play();
  }, [actions]);

  // Handle animation transitions without triggering React renders
  useFrame(() => {
    let nextAction: ActionName = 'idle';

    // Check velocity
    if (bodyRef.current && group.current) {
      const velocity = bodyRef.current.linvel();
      const speed = Math.sqrt(velocity.x ** 2 + velocity.z ** 2);

      if (speed > 0.5) { // Lowered detection threshold for slower walk cycles
        // Convert world velocity to local velocity to know which way we are strafing relative to where we are aiming
        const localVel = new THREE.Vector3(velocity.x, 0, velocity.z);
        const quaternion = new THREE.Quaternion();
        group.current.getWorldQuaternion(quaternion);
        quaternion.invert();
        localVel.applyQuaternion(quaternion);

        // In our setup, Z+ is forward due to the way lookAt is configured in Player.tsx
        const fwd = localVel.z;
        const right = -localVel.x; // ThreeJS standard: X- is right if Z+ is forward

        const threshold = speed * 0.4; // Diagonal threshold

        const state = moveStateRef.current || 'run';
        if (state === 'roll') {
          nextAction = 'Sprinting Forward Roll';
        } else {
          let prefix: string = state;
          if (state === 'crouch') prefix = 'walk crouching';

          if (fwd > threshold && right > threshold) nextAction = `${prefix} forward right` as ActionName;
          else if (fwd > threshold && right < -threshold) nextAction = `${prefix} forward left` as ActionName;
          else if (fwd < -threshold && right > threshold) nextAction = `${prefix} backward right` as ActionName;
          else if (fwd < -threshold && right < -threshold) nextAction = `${prefix} backward left` as ActionName;
          else if (fwd > threshold) nextAction = `${prefix} forward` as ActionName;
          else if (fwd < -threshold) nextAction = `${prefix} backward` as ActionName;
          else if (right > threshold) nextAction = `${prefix} right` as ActionName;
          else if (right < -threshold) nextAction = `${prefix} left` as ActionName;
          else nextAction = `${prefix} forward` as ActionName; // fallback
        }
      } else {
        // Idle State
        const state = moveStateRef.current || 'run';
        if (state === 'roll') {
          nextAction = 'Sprinting Forward Roll';
        } else if (state === 'crouch') {
          nextAction = 'idle crouching';
        } else {
          nextAction = 'idle';
        }

        // Check shooting overrides
        if (isShootingRef.current) {
          if (moveStateRef.current === 'crouch') nextAction = 'idle crouching aiming';
          else nextAction = 'idle aiming';
        }
      }
    }

    // Transition if changed
    if (nextAction !== currentAction.current) {
      actions[currentAction.current]?.fadeOut(0.2);
      const action = actions[nextAction];
      if (action) {
        action.reset().fadeIn(0.2).play();
        if (nextAction === 'Sprinting Forward Roll') {
          action.setLoop(THREE.LoopOnce, 1);
          action.clampWhenFinished = true;
          action.setEffectiveTimeScale(1.6); // 60% faster
        } else {
          action.setLoop(THREE.LoopRepeat, Infinity);
          action.setEffectiveTimeScale(1.0); // Reset to normal
        }
      }
      currentAction.current = nextAction;
    }
  });

  useImperativeHandle(ref, () => ({
    getMuzzlePosition: () => weaponRef.current?.getWorldPosition() || new THREE.Vector3()
  }));

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
      {rightHandBone && (
        <group ref={weaponGroupRef}>
          <M4A1 ref={weaponRef} />
        </group>
      )}
    </group>
  )
});

BonecoCompleto.displayName = 'BonecoCompleto';

useGLTF.preload('/models/Player.glb')
