/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Boneco_Completo.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'
import { RapierRigidBody } from '@react-three/rapier'

type ActionName =
  | 'mixamo.com'
  | 'Take 001'
  | 'sprint backward'
  | 'sprint left'
  | 'sprint right'
  | 'turn 90 right'
  | 'walk backward left'
  | 'walk backward right'
  | 'walk backward'
  | 'walk crouching backward left'
  | 'walk crouching backward right'
  | 'walk crouching backward'
  | 'walk crouching forward left'
  | 'walk crouching forward'
  | 'walk crouching left'
  | 'walk crouching right'
  | 'walk forward left'
  | 'walk forward right'
  | 'walk forward'
  | 'walk left'
  | 'walk right'
  | 'idle crouching'
  | 'idle'
  | 'run backward left'
  | 'run backward right'
  | 'run backward'
  | 'run forward left'
  | 'run forward right'
  | 'run forward'
  | 'run left'
  | 'run right'
  | 'sprint forward left'
  | 'sprint forward right'
  | 'sprint forward'
  | 'turn 90 left'
  | 'walk crouching forward right'
  | 'crouching turn 90 left'
  | 'crouching turn 90 right'
  | 'death crouching headshot front'
  | 'death from back headshot'
  | 'death from front headshot'
  | 'death from right'
  | 'death from the back'
  | 'death from the front'
  | 'idle aiming'
  | 'idle crouching aiming'
  | 'jump down'
  | 'jump loop'
  | 'jump up'
  | 'sprint backward left'
  | 'sprint backward right'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Beta_Surface: THREE.SkinnedMesh
    Beta_Joints: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Beta_HighLimbsGeoSG3: THREE.MeshStandardMaterial
    Beta_Joints_MAT1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type BonecoProps = React.ComponentProps<'group'> & {
  bodyRef: React.RefObject<RapierRigidBody | null>;
  isShootingRef: React.RefObject<boolean>;
};

export function BonecoCompleto({ bodyRef, isShootingRef, ...props }: BonecoProps) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Boneco_Completo.glb')
  
  // Mixamo Root Motion Fix ("In Place" hook)
  const inPlaceAnimations = React.useMemo(() => {
    return animations.map(clip => {
      const clonedClip = clip.clone();
      clonedClip.tracks.forEach(track => {
         // Check for the main hip translation track
         if (track.name.match(/mixamorigHips\.position/i)) {
            // track.values is a flat array [X, Y, Z, X, Y, Z, ...]
            for (let i = 0; i < track.values.length; i += 3) {
               // Zero out X and Z (Forward/Lateral movement)
               track.values[i] = 0;     
               // Keep Y (track.values[i + 1]) for bounce/bobbing
               track.values[i + 2] = 0; 
            }
         }
      });
      return clonedClip;
    });
  }, [animations]);

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(inPlaceAnimations, group)

  const currentAction = useRef<ActionName>('idle');

  // Play initial animation
  useEffect(() => {
    actions[currentAction.current]?.play();
  }, [actions]);

  // Handle animation transitions without triggering React renders
  useFrame(() => {
    let nextAction: ActionName = 'idle';
    
    // Check velocity
    if (bodyRef.current && group.current) {
        const velocity = bodyRef.current.linvel();
        const speed = Math.sqrt(velocity.x ** 2 + velocity.z ** 2);
        
        if (speed > 1) {
            // Convert world velocity to local velocity to know which way we are strafing relative to where we are aiming
            const localVel = new THREE.Vector3(velocity.x, 0, velocity.z);
            const quaternion = new THREE.Quaternion();
            group.current.getWorldQuaternion(quaternion);
            quaternion.invert();
            localVel.applyQuaternion(quaternion);

            // In our setup, Z+ is forward due to the way lookAt is configured in Player.tsx
            const fwd = localVel.z;
            const right = -localVel.x; // ThreeJS standard: X- is right if Z+ is forward

            const threshold = speed * 0.4; // Diagonal threshold

            if (fwd > threshold && right > threshold) nextAction = 'run forward right';
            else if (fwd > threshold && right < -threshold) nextAction = 'run forward left';
            else if (fwd < -threshold && right > threshold) nextAction = 'run backward right';
            else if (fwd < -threshold && right < -threshold) nextAction = 'run backward left';
            else if (fwd > threshold) nextAction = 'run forward';
            else if (fwd < -threshold) nextAction = 'run backward';
            else if (right > threshold) nextAction = 'run right';
            else if (right < -threshold) nextAction = 'run left';
            else nextAction = 'run forward'; // fallback
        }
    }

    // Check shooting
    if (isShootingRef.current && nextAction === 'idle') {
        nextAction = 'idle aiming';
    }

    // Transition if changed
    if (nextAction !== currentAction.current) {
        actions[currentAction.current]?.fadeOut(0.2);
        actions[nextAction]?.reset().fadeIn(0.2).play();
        currentAction.current = nextAction;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Beta_Surface" geometry={nodes.Beta_Surface.geometry} material={materials.Beta_HighLimbsGeoSG3} skeleton={nodes.Beta_Surface.skeleton} />
          <skinnedMesh name="Beta_Joints" geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT1} skeleton={nodes.Beta_Joints.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Boneco_Completo.glb')
