/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Zombie_Completo.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'
import { RapierRigidBody } from '@react-three/rapier'

type ActionName = 'mixamo.com' | 'Take 001' | 'zombie run' | 'zombie scream' | 'zombie walk' | 'running crawl' | 'zombie attack' | 'zombie biting (2)' | 'zombie biting' | 'zombie crawl' | 'zombie death' | 'zombie dying' | 'zombie idle' | 'zombie neck bite'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Beta_Surface: THREE.SkinnedMesh
    Beta_Joints: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Beta_HighLimbsGeoSG3: THREE.MeshStandardMaterial
    Beta_Joints_MAT1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type EnemyState = 'IDLE' | 'WANDER' | 'INVESTIGATE' | 'CHASE' | 'ATTACK' | 'DEAD';

type ZombieProps = React.ComponentProps<'group'> & {
  bodyRef: React.RefObject<RapierRigidBody | null>;
  state: EnemyState;
};

export function ZombieCompleto({ bodyRef, state, ...props }: ZombieProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Zombie_Completo.glb')
  
  // Mixamo Root Motion Fix ("In Place" hook)
  const inPlaceAnimations = React.useMemo(() => {
    return animations.map(clip => {
      const clonedClip = clip.clone();
      clonedClip.tracks.forEach(track => {
         if (track.name.match(/mixamorigHips\.position/i)) {
            for (let i = 0; i < track.values.length; i += 3) {
               track.values[i] = 0;     // X
               track.values[i + 2] = 0; // Z
            }
         }
      });
      return clonedClip;
    });
  }, [animations]);

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(inPlaceAnimations, group)

  const currentAction = React.useRef<ActionName>('zombie idle');

  // Play initial
  React.useEffect(() => {
    actions[currentAction.current]?.play();
  }, [actions]);

  // Handle animation transitions based on EnemyState
  React.useEffect(() => {
    let nextAction: ActionName = 'zombie idle';
    
    switch (state) {
        case 'IDLE':
            nextAction = 'zombie idle';
            break;
        case 'WANDER':
        case 'INVESTIGATE':
            nextAction = 'zombie walk';
            break;
        case 'CHASE':
            nextAction = 'zombie run';
            break;
        case 'ATTACK':
            nextAction = 'zombie attack';
            break;
        case 'DEAD':
            nextAction = 'zombie death';
            break;
    }

    if (nextAction !== currentAction.current) {
        const action = actions[nextAction];
        if (action) {
            if (nextAction === 'zombie death') {
                // Instant snap to death, no crossfade
                actions[currentAction.current]?.fadeOut(0.0);
                action.reset().fadeIn(0.0).play();
                action.setLoop(THREE.LoopOnce, 1);
                action.clampWhenFinished = true;
            } else {
                actions[currentAction.current]?.fadeOut(0.2);
                action.reset().fadeIn(0.2).play();
                action.setLoop(THREE.LoopRepeat, Infinity);
            }
        }
        currentAction.current = nextAction;
    }
  }, [state, actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Beta_Surface" geometry={nodes.Beta_Surface.geometry} material={materials.Beta_HighLimbsGeoSG3} skeleton={nodes.Beta_Surface.skeleton} />
          <skinnedMesh name="Beta_Joints" geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT1} skeleton={nodes.Beta_Joints.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Zombie_Completo.glb')
